### ISSUE TITLE
size of the inputs and outputs of the u-net

### ISSUE THREAD

**Issue by mathxiaobin** [jakeoung/u-net_pytorch#1]
I am using this code to run my own data, but it seems that my data's size is not right.Could you please tell me the sizes of the inputs and outputs of your u-net?

**Comment by jakeoung** [comment]
In `model.py`, there are 4 max pooling operations. In my current implementation, your image should have the size whose dimensions are divisible by 16.

For example, my test image has size of [560 x 400]. Both dimensions can be divided by 16.

**Comment by mathxiaobin** [comment]
thank you
