### ISSUE TITLE
RuntimeError: inconsistent tensor sizes  at THCTensorMath.cu:141

### ISSUE THREAD

**Issue by yghlc** [jakeoung/u-net_pytorch#3]
Hi, 
    This error occurred when I input images with different size. I set 
   `  self.nRow = 480
     self.nCol = 480`.
    The size of input images could be 320 by 480 or 480 by 480. It was ok when input first several images with 320 by 480, but when input an image with 480 by 480, this error occurred. 
    I appreciated any suggestion to fix this error. Thanks!

**Comment by jakeoung** [comment]
The problem may be from cropping image in the dataset code. So it is better to resize image. Do you need help? Then, I can update my code.

**Comment by yghlc** [comment]
Thanks!
I already resize the image in my fork version. Sorry for forgetting to update the issue.

**Comment by jakeoung** [comment]
Okay! (If possible, could you do pull-request for that?)

**Comment by yghlc** [comment]
I have changed a lot since I need to process the remote sensing images. I'm not sure whether it is easy for you to check all the codes. 

I create a new file named test.py. The following is the codes I resize the image:

`  b_crop = False
    x_shape = x.size()
    if x_shape[2] < datasetRS.crop_height or x_shape[3] < datasetRS.crop_width:
        b_crop = True
        x_expand = torch.zeros(x_shape[0],x_shape[1],datasetRS.crop_height,datasetRS.crop_width)
        x_expand[:,:,:x_shape[2],:x_shape[3]] = x
        y_pred = model(Variable(x_expand.cuda()))
    else:
        y_pred = model(Variable(x.cuda()))

    if b_crop is True:
        x = x_expand[:,:,:x_shape[2],:x_shape[3]]
        y_pred = y_pred[:,:,:x_shape[2],:x_shape[3]]
`

**Comment by jakeoung** [comment]
Okay, thank you very much^^
